name: SwiftUITabPagerSample
options:
  bundleIdPrefix: com.camosss
  deploymentTarget:
    iOS: "15.0"
packages:
  SwiftUITabPager:
    path: ../..
targets:
  SwiftUITabPagerSample:
    type: application
    platform: iOS
    sources:
      - SwiftUITabPagerSample
    dependencies:
      - package: SwiftUITabPager
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGNING_ALLOWED: NO
